### ISSUE TITLE
SDF unreadable? (tried all available encodings)

### ISSUE THREAD

**Issue by alakifan** [cheminfo/sdf-parser#13]
Parsing my sdf file like this:

> const sdf = readFileSync('./src/config/sdf-full.sdf', 'utf8')
> const result = parse(sdf)
> console.log(result)

returns a corrupt array of some sort

`{
  time: 44,
  molecules: [
    {
      molfile: '�ZYM\x00\x00\x00\x00\x04\x00\x00\x00\x00\x00\x00\x00�{5\x00\x01\x00\x00\x00�\x03\x00\x00\x00\x00\x00\x00\x11\x00\x00\x00\x00\x00\x00\x00\t\x04\x00\x00�\x0B\x00\x00\x03\x00\x05\x00�\x1F\x00\x00\x00\x00\x00\x00\t\x00\x00\x00�\x00\x00\x00�!\x00\x00\x06\x00\x01�\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00...
}
  ],
  labels: [ '\x18\x02�<', '' ]`

**Comment by lpatiny** [comment]
You should zip and upload your SDF in this issue

**Comment by alakifan** [comment]
> You should zip and upload your SDF in this issue

@lpatiny You're right, apologies

[sdf-full.zip](https://github.com/cheminfo/sdf-parser/files/10554959/sdf-full.zip)

**Comment by targos** [comment]
This looks like a binary file (of currently undetermined format/contents). SDF is a text file format, so we cannot parse your file.
